apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hodei-devops.fullname" . }}-jwt
  labels:
    {{- include "hodei-devops.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-access-secret: {{ .Values.jwt.accessSecret | default .Values.jwt.secret | b64enc }}
  jwt-refresh-secret: {{ .Values.jwt.refreshSecret | default .Values.jwt.secret | b64enc }}