apiVersion: v1
kind: Secret
metadata:
  name: hodei-mongodb
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.rootPassword | b64enc }}
  mongodb-password: {{ .Values.mongodb.password | b64enc }}
  mongodb-user: {{ .Values.mongodb.username | b64enc }}