apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hodei-devops.fullname" . }}-tls
  labels:
    {{- include "hodei-devops.labels" . | nindent 4 }}
    app: {{ .Values.hodeiApp.name | default "hodei-app" }}
type: Opaque
data:
  {{- $ctx := dict "Files" .Files "Path" .Values.certs.ca }}
  {{- if ne .Values.certs.ca "" }}
    {{- if ne (include "hodei-devops.fileExists" $ctx) "true" }}
      {{- fail (printf "Archivo no encontrado: %s. Búsqueda desde la raíz del chart" .Values.certs.ca) }}
    {{- end }}
  ca.crt: {{ tpl (.Files.Get .Values.certs.ca) . | b64enc }}
  {{- end }}

  {{- $ctx = dict "Files" .Files "Path" .Values.certs.server }}
  {{- if ne .Values.certs.server "" }}
    {{- if ne (include "hodei-devops.fileExists" $ctx) "true" }}
      {{- fail (printf "Archivo no encontrado: %s. Búsqueda desde la raíz del chart" .Values.certs.server) }}
    {{- end }}
  server.crt: {{ tpl (.Files.Get .Values.certs.server) . | b64enc }}
  {{- end }}

  {{- $ctx = dict "Files" .Files "Path" .Values.certs.serverKey }}
  {{- if ne .Values.certs.serverKey "" }}
    {{- if ne (include "hodei-devops.fileExists" $ctx) "true" }}
      {{- fail (printf "Archivo no encontrado: %s. Búsqueda desde la raíz del chart" .Values.certs.serverKey) }}
    {{- end }}
  server.key: {{ tpl (.Files.Get .Values.certs.serverKey) . | b64enc }}
  {{- end }}

  {{- $ctx = dict "Files" .Files "Path" .Values.certs.client }}
  {{- if ne .Values.certs.client "" }}
    {{- if ne (include "hodei-devops.fileExists" $ctx) "true" }}
      {{- fail (printf "Archivo no encontrado: %s. Búsqueda desde la raíz del chart" .Values.certs.client) }}
    {{- end }}
  client.crt: {{ tpl (.Files.Get .Values.certs.client) . | b64enc }}
  {{- end }}

  {{- $ctx = dict "Files" .Files "Path" .Values.certs.clientKey }}
  {{- if ne .Values.certs.clientKey "" }}
    {{- if ne (include "hodei-devops.fileExists" $ctx) "true" }}
      {{- fail (printf "Archivo no encontrado: %s. Búsqueda desde la raíz del chart" .Values.certs.clientKey) }}
    {{- end }}
  client.key: {{ tpl (.Files.Get .Values.certs.clientKey) . | b64enc }}
  {{- end }}