version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: build/server/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - GRPC_PORT=50051
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 5s
      timeout: 3s
      retries: 3

  client:
    build:
      context: .
      dockerfile: build/client/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
      - GRPC_SERVER=server:50051
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 3 