services:
  orchestrator:
    container_name: hodei-orchestrator
    build:
      context: .
      dockerfile: build/orchestrator/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - CLIENT_CERT_PATH=/certs/worker-client-cert.pem
      - CLIENT_KEY_PATH=/certs/worker-client-key.pem
      - CA_CERT_PATH=/certs/ca-cert.pem
      - JWT_TOKEN=${JWT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - WORKER_IMAGE=hodei/remote-process-worker:latest
      - DOCKER_NETWORK=orchestrator-test
      - PB_SKIP_INIT=true
      - PB_ADDR=0.0.0.0:8090
    volumes:
      - ./hodei-chart/certs/dev:/certs:ro
      - ./test_pb_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - orchestrator-test
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8090/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  orchestrator-test:
    external: true

